### ISSUE TITLE
Uncaught TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by aerni** [FrancescoSaverioZuppichini/API-Class#11]
Thanks for this amazing utility! I can't seem to make it work though. I followed the instructions. This is my code:

```
import API from 'api-class';

const myAPI = new API({ url: 'http://baerenmatte.test/api' });

myAPI.createEntity({ name: 'events' });
myAPI.endpoints.events.getAll()
  .then(({data}) => console.log(data));
```

And this is the error I get in the console:

```
API.js:68 Uncaught TypeError: Cannot read property 'query' of undefined
    at Object.endpoints.getAll (API.js:68)
    at Module.<anonymous> (app.js:102)
    at Module../site/resources/js/app.js (app.js:30155)
    at __webpack_require__ (bootstrap:19)
    at Object.0 (app.js:31559)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```

What am I doing wrong?

**Comment by aerni** [comment]
Ok, I found I have to pass arguments to the `getAll()` method like this:

```
let query = {};
let config = {};
myAPI.endpoints.events.getAll(query, config)
```

Can we make the `query` and `config` optional? And please excuse me for this stupid question, but what does the `query` and `config` do anyways?

**Comment by aerni** [comment]
I read up on the axios documentation. I now get how `query` works. But I can't seem to make it work. The URL I want to fetch including the query string looks like this: `http://baerenmatte.test/!/fetch/collection/events?limit=1`. 

I now want pass this query `&limit=1` to the `getAll()` method like so:
```
let query = {
  limit: 1
}
myAPI.endpoints.events.getAll(query, config)
```
However, this doesn't work. It doesn't give me back the right output. It's like the query is not added to the URL at all.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi, if your server is expecting url encoded arguments you should url encode them.

This is what is going on under the hood:

```
    endpoints.getAll = ({ query={}}, config={} ) => axios.get(resourceURL, Object.assign({ params: { query }}, config))
```

I am not actually sure how to tell axios to URL encode those parameters

**Comment by aerni** [comment]
Axios automatically converts the `params` to URL queries. Both code examples below will have the same response.

Directly passing queries tot the URL:
```
axios.get('http://baerenmatte.test/api/events?limit=2')
```

Using the `params` object instead:
```
axios.get('http://baerenmatte.test/api/events', {
  params: {
    limit: 2
  }
})
```

I'm a bit confused. What's the `query` in the `getAll()` method used for if not passing queries to the Axios `params` object?

**Comment by FrancescoSaverioZuppichini** [comment]
Oh, I know why. I will fix the bug in 1 hour.

**Comment by FrancescoSaverioZuppichini** [comment]
Try now, you now have to pass `params` instead of `query`

**Comment by aerni** [comment]
Hmm, I'm sorry. Still doesn't work. Am I doing something wrong here?

```
const myAPI = new API({ url: '/!/fetch/collection' });

let params = {
  limit: 1
}

let config = {};

myAPI.createEntity({ name: 'events' });
myAPI.endpoints.events.getAll(params, config)
  .then(({ data }) => console.log(data))
```

**Comment by FrancescoSaverioZuppichini** [comment]
You can avoid setting config. I don't know, it should be fine. Try to update the package and re-run, now it should work. I was not able to test it from mocha because I am lazy but it should be fine :)

**Comment by aerni** [comment]
Ok, I got it. As expected it was a mistake on my side. I missed to wrap `params` in the `getAll()` method with `{}`.

This is working now as expected:
```
const myAPI = new API({ url: '/!/fetch/collection' });

let params = {
  limit: 1
}

myAPI.createEntity({ name: 'events' });
myAPI.endpoints.events.getAll({params})
  .then(({ data }) => console.log(data));
```

Thanks for your time and fix!

**Comment by FrancescoSaverioZuppichini** [comment]
Mmm, with the update I am not sure this will work again. Can you update and try it again please? :)

**Comment by aerni** [comment]
I checked. The code above is still working on api `version 0.0.6`

**Comment by FrancescoSaverioZuppichini** [comment]
Perfect :)
