### ISSUE TITLE
Set optional headers for authentication

### ISSUE THREAD

**Issue by patronelli87** [FrancescoSaverioZuppichini/API-Class#6]
Please, add headers parameters as an option to authenticate a token.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi, I will do that tomorrow :)

**Comment by FrancescoSaverioZuppichini** [comment]
In the latest push you can now pass a config obj to each call:

```
const myAPI = new API({ url: '/api' })
myAPI.getOne({ id: 0 },  { headers: {....} } )
```
The second parameters is a config obj that is passed to axios. Can you test it and let me know if it works?

**Comment by patronelli87** [comment]
Thank you! Sure. I'll test it.

**Comment by patronelli87** [comment]
Tested. Works good!

**Comment by FrancescoSaverioZuppichini** [comment]
Perfect :)
