### ISSUE TITLE
Hyphens

### ISSUE THREAD

**Issue by williamabbott** [FrancescoSaverioZuppichini/API-Class#7]
What if the resourceUrl path has a hyphen?

`API.createEntity({ name: 'data-systems' });`

**Comment by FrancescoSaverioZuppichini** [comment]
Hi, 

I don't see the problem

**Comment by Uneetpatel7** [comment]
How can I use resource URL with '-'? Please provide an example for the same

**Comment by FrancescoSaverioZuppichini** [comment]
The following snippet

```
const myAPI = new API({ url: '/api' })
```
does not work? Can you share the error's output?

**Comment by Uneetpatel7** [comment]
It does work. My question is I want to fetch from a URL like this `http://localhost:8080/api/post-feedback` :
If I create an API instance `const myApi = new API({ url:'http://localhost:8080/api' })` and then creating all handles for post-feedback entity with `myApi.createEntity({ name: 'posts' })`. But I cannot use it like  `myApi.endpoints.posts-feedback.getAll()`. Is there any workaround for this

**Comment by FrancescoSaverioZuppichini** [comment]
Okay, I understand. I will parse the `name` param from `createEntity` and convert it to camelCase if there is a `-`. Something like this:

```
const myApi = new API({ url:'http://localhost:8080/api' })
myApi.createEntity({ name: 'post-feedback' })
myApi.endpoints.postsFeedback.getAll()
```

Does it sound good? I will have time tomorrow to push the fix

**Comment by FrancescoSaverioZuppichini** [comment]
Okay, since you are passing a kebab case string, js cannot use the `.fieldName` notation. You have to directly call the dictionary
```
myApi.endpoints.['posts-feedback'].getAll()
```

**Comment by Uneetpatel7** [comment]
I knew the work around. Even I did the same for my project. But it’s better if we have some sort of uniformity I guess.

**Comment by FrancescoSaverioZuppichini** [comment]
Fixed. When passing an entity with a name in kebab-case it will be converted to CamelCase
```
myApi.createEntity({ name : 'foo-bar'})
myApi.endpoints.fooBar.getAll(...)
```
check also the [test](https://github.com/FrancescoSaverioZuppichini/API-Class/blob/master/test/test.js#L27)

Let me know if it is working!
