### ISSUE TITLE
getAll method is not handling headers properly

### ISSUE THREAD

**Issue by vrajeshkanna** [FrancescoSaverioZuppichini/API-Class#9]
Current code

https://github.com/FrancescoSaverioZuppichini/API-Class/blob/63bef069845e9dc7cae3effb89f53f0fb244cb0b/source/API.js#L41

`    endpoints.getAll = ({ query={}}, config={} ) => axios.get(resourceURL, Object.assign({ params: { query }, config }))
`

here the merge is not happening properly, because of which headers are not sent.

The below code will fix the problem

`Object.assign({ params: { query } }, config)`

BTW all other methods are working fine

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @vrajeshkanna,

could you please make a PR and show also a not-working example?

Thank you :)

**Comment by vrajeshkanna** [comment]
Hi @FrancescoSaverioZuppichini 
I have created PR #10 with working and non-working examples
